---
title: "Random Forest Extraction"
author: "Thiago Orlando Costa Barboza"
date: "2025-05-02"
output: pdf_document
---

```{r, Install packages for use}

#1° install the packages:
install.packages(c('terra','mapview','sf','stars','caret','mapedit','devtools',"dplyr",
                   "fields","leafem","leafsync","lwgeom","BiocManager","git2r","exactextractr","rgdal" ))

#2° install the dependency for FieldImageR:
BiocManager::install("EBImage")

#3° install FIELDimageR and FieldImageR.extra:
devtools::install_github("OpenDroneMap/FIELDimageR")
devtools::install_github("filipematias23/FIELDimageR.Extra")
```


```{r, call the libraries}

library(webshot)
library(webshot2)
library(tinytex)
library(rmarkdown)
library(raster)
library(FIELDimageR)
library(FIELDimageR.Extra)
library(terra)
library(mapview)
library(sf)
library(stars)
library(nlme)
library(imager)
library(leafsync)
library(pliman)
library(gdalUtilities)
library(ggplot2)
library(gridExtra)
library(RStoolbox)
library(patchwork)
library(tidyr)
```


```{r, insert the path for each bands or the orthomosaic image}

banda_r <- rast("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/processing_transparent_reflectance_red.tif") 

banda_g <- rast("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/processing_transparent_reflectance_green.tif")  

#When you're using the mavic you don't have the blue band
banda_b <- rast("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/processing_transparent_reflectance_green.tif")  

banda_re <- rast("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/processing_transparent_reflectance_red edge.tif")  

banda_nir <- rast("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/processing_transparent_reflectance_nir.tif")  

# the 1° option you're jointing the bands in one file (bandset)
bandset <- c(banda_r, banda_g, banda_b, banda_re, banda_nir)
```


```{r, insert the path for orthomosaic}

#the 2° option: you can also use only the orthomosaic/reflectance map, if you already join the bands in one file
#bandset <-rast("")
```


```{r, Open the bandset (orthomosaic)}

# Function to open the bandset
plotRGB(bandset, r = 1, g = 2, b = 4)

# if you need to save the bandset, use this option
writeRaster(bandset, "C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/bandset.tif", overwrite = TRUE)

```


```{r, open the image in webshot}

#open the save orthomosaic again
bandset <- rast("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/bandset.tif")

#this function you can see your raster image
fieldView(bandset)
```


```{r, clip the orthomosaic and open}

#if you need to clip the raster image use the AOI below
#editor equal TRUE open the editor
aoi<-fieldView(bandset,editor = TRUE) 

#here you can put your polygon if you draw in the QGIS, ARCgis, etc.
#aoi <- st_read('C:/Users/THIAGO COSTA/OneDrive/Área de Trabalho/amrinder/poligono.shp') 

#clip the bandset in the interest field
bandset_1 <- crop(bandset, aoi) 

#Open the clipped bandset
fieldView(bandset_1) #plot the bandset
```


```{r,index calculation}

#for the classification you can calculate a index (NDVI) to improve the classification
#pass the information of the sequence of the banset that you used in the 'c()'
#using the function 'myindex' you can add manually your index
indices <- fieldIndex(bandset_1, 
                      Red = 1, 
                      Green = 2, 
                      Blue = 3, 
                      RedEdge = 4, 
                      NIR = 5,
                      index = c("SCI", "NDRE", "NDVI")) 

fieldView(bandset_1)
#fieldView(indices$NIR)
```


```{r, creating the soil and plant samples for classification}
#create the soil and plant samples
# Digitize soil object by drawing polygons at least 5-6 large polygon uniformly distributed
#generate random 400 points for soil class
orto <- bandset_1
soil<-fieldView(mosaic = orto, editor = TRUE) 
soil<-st_as_sf(st_sample(soil, 400))
soil$class<-'soil'

# Digitize plants object by drawing polygons 
#The number of polygon will depends upon the number of training points to be generated
#generate random 400 points for plants class
plants<-fieldView(mosaic = orto, editor = TRUE)
plants<-st_as_sf(st_sample(plants, 400))
plants$class<-'plants'

#You also can add more class like forest, water, etc.
```
```{r, visualizing the poitn generated}

#Add the orthomosaic and the points generate to visualize
#you also can add the vegetation index
fieldView(bandset, plants)

```

```{r, training the RF model}

#Make unique raster
names(bandset_1) <- make.unique(names(bandset_1))

#joining all class in one file
training_sam<-rbind(soil,plants)

#Creating some samples
samples = as(training_sam, "Spatial")

#training the RF model using the samples
result = superClass(
 bandset_1, 
 trainData = samples,
 responseCol = "class",
 model = "rf",
 tuneLength = 3,
 kfold = 5,
 trainPartition = 0.7
)

#plot the classify map
plot(result$map)
fieldView(bandset_1, result$map)

#plot the model performance on validation
print(result$validation$performance)
```


```{r, clip the original bandset and save the new map}

#creating a mask and remove the soil
soilmask = result$map == 1
ortosolo = mask(bandset_1, soilmask, maskvalue = 0)
plot(ortosolo[[1]])


# Converter para dataframe plotável
df_solo <- as.data.frame(ortosolo[[1]], xy = TRUE, na.rm = TRUE)

# Criar e salvar o gráfico
plot <- ggplot(df_solo, aes(x = x, y = y, fill = names(df_solo)[3])) +
  geom_raster() +
  scale_fill_viridis_d(name = "Valor") +
  labs(color = "Plants")+
  labs(title = "Remove soil map") +
  theme_bw() + 
  theme(legend.position = "Top")
plot

#save the map
ggsave("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/soil_remove_ortho.png", 
       plot, width = 8, height = 8, dpi = 600)

```


```{r, save the raster image}
#save the orginal image with soil clip
writeRaster(raster(ortosolo), 
            filename = "C:/Users/THIAGO/Desktop/projeto_trainee_gepad/drone_ms/class_orto.tif", 
            format = "GTiff")
```


```{r, loading the plots to extract the values}

#loading the plots
plots <- st_read("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/treatments/midville_plots.geojson")

#Applu the buffer for the plots
plots <- st_buffer(plots, dist = -2)

#plot the results of the classification with the plots
fieldView(ortosolo,
          fieldShape = plots,
          type = 2,
          alpha_grid = 0.2)
```


```{r, calculate some vegetation index}

#Calculate the index again without soil
resultados <- mosaic_index(
  ortosolo, 
  index = c("NDVI", "GLI", "NDRE", "GNDVI"), 
  r = 1, 
  g = 2, 
  b = 3 , 
  re = 4, 
  nir = 5
)

plot(resultados$NDRE)
```


```{r, extracting the mean values and save}

#extract the values using the mean
DataTotal<- fieldInfo_extra(
  mosaic = resultados,
  fieldShape = plots, 
  fun = "mean") #extracting the data

DataTotal

#if you want to save the csv file 
write.csv(DataTotal, "C:/Users/THIAGO/Desktop/projeto_trainee_gepad/csv/data_total.csv", row.names = TRUE)
```

```{r, save the vegetation index}

#if you want to save the raster images use the function below
writeRaster(raster(index_extraction$NDVI), filename = "C:/thiago_eua/IH/mavic/07_10/processing/4_index/reflectance/NDVI.tif",
            format = "GTiff")
writeRaster(raster(index_extraction$GNDVI), filename = "GNDVI.tif", format = "GTiff")
writeRaster(raster(index_extraction$NDRE), filename = "NDRE.tif", format = "GTiff")
writeRaster(raster(index_extraction$NDRE), filename = "NDRE.tif", format = "GTiff")

```


```{r, plotting the classify map using ggplot}

#Convert the raster in a dataframe
df_mosaic <- as.data.frame(resultados, xy = TRUE)

#plotting the map using the ggplot function
p1<- ggplot(df_mosaic, aes(x = x, y = y, fill = NDVI)) +
  geom_raster() +
  scale_fill_viridis_c(name = "NDVI") +
  labs(title = "Vegetation Index Map") +
  theme_bw() +
  theme(legend.position = "bottom")
p1
```
```{r, plot all VI}

#create a new dataframe with pivot longer
df_long <- df_mosaic %>%
  pivot_longer(cols = c(NDVI, GLI, NDRE, GNDVI),
               names_to  = "indice",
               values_to = "valor")

#plotting the vegetation index
p2 <- ggplot(df_long, aes(x = x, y = y, fill = valor)) +
  geom_raster() +
  scale_fill_viridis_c() +
  facet_wrap(~ indice, scales = "free") +
  labs(fill = "Value", title = "Vegetation Index Map") +
  theme_bw() +
  theme(legend.position = "bottom")
p2

#save the file
ggsave("C:/Users/THIAGO/Desktop/projeto_trainee_gepad/results/VI_map.png", p2, 
       width = 10, height = 10, dpi = 600)
```

